#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : glmark2
Version  : 24a1139dcbfd86bd02065316eaa90559e39374e1
Release  : 5
URL      : https://github.com/glmark2/glmark2/archive/24a1139dcbfd86bd02065316eaa90559e39374e1/24a1139dcbfd86bd02065316eaa90559e39374e1.tar.gz
Source0  : https://github.com/glmark2/glmark2/archive/24a1139dcbfd86bd02065316eaa90559e39374e1/24a1139dcbfd86bd02065316eaa90559e39374e1.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-3.0 Libpng MIT X11
Requires: glmark2-bin = %{version}-%{release}
Requires: glmark2-data = %{version}-%{release}
Requires: glmark2-license = %{version}-%{release}
Requires: glmark2-man = %{version}-%{release}
BuildRequires : apache-ant
BuildRequires : buildreq-cmake
BuildRequires : buildreq-mvn
BuildRequires : libjpeg-turbo-dev
BuildRequires : libpng-dev
BuildRequires : mesa-dev
BuildRequires : pkgconfig(wayland-client)
BuildRequires : systemd-dev
Patch1: 0001-build.patch

%description
glmark2 is an OpenGL 2.0 and ES 2.0 benchmark.
glmark2 is developed by Alexandros Frantzis and Jesse Barker based on the
original glmark benchmark by Ben Smith.

%package bin
Summary: bin components for the glmark2 package.
Group: Binaries
Requires: glmark2-data = %{version}-%{release}
Requires: glmark2-license = %{version}-%{release}

%description bin
bin components for the glmark2 package.


%package data
Summary: data components for the glmark2 package.
Group: Data

%description data
data components for the glmark2 package.


%package license
Summary: license components for the glmark2 package.
Group: Default

%description license
license components for the glmark2 package.


%package man
Summary: man components for the glmark2 package.
Group: Default

%description man
man components for the glmark2 package.


%prep
%setup -q -n glmark2-24a1139dcbfd86bd02065316eaa90559e39374e1
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1570815389
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -falign-functions=32 -ffat-lto-objects -flto=4 -fno-math-errno -fno-semantic-interposition -fno-trapping-math "
export FCFLAGS="$CFLAGS -O3 -falign-functions=32 -ffat-lto-objects -flto=4 -fno-math-errno -fno-semantic-interposition -fno-trapping-math "
export FFLAGS="$CFLAGS -O3 -falign-functions=32 -ffat-lto-objects -flto=4 -fno-math-errno -fno-semantic-interposition -fno-trapping-math "
export CXXFLAGS="$CXXFLAGS -O3 -falign-functions=32 -ffat-lto-objects -flto=4 -fno-math-errno -fno-semantic-interposition -fno-trapping-math "
make  %{?_smp_mflags}


%install
export SOURCE_DATE_EPOCH=1570815389
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/glmark2
cp %{_builddir}/glmark2-24a1139dcbfd86bd02065316eaa90559e39374e1/COPYING %{buildroot}/usr/share/package-licenses/glmark2/8624bcdae55baeef00cd11d5dfcfa60f68710a02
cp %{_builddir}/glmark2-24a1139dcbfd86bd02065316eaa90559e39374e1/COPYING.SGI %{buildroot}/usr/share/package-licenses/glmark2/f044eb2afb2cff19b88e39a1d96d78c9d8bd2bfa
cp %{_builddir}/glmark2-24a1139dcbfd86bd02065316eaa90559e39374e1/src/libjpeg-turbo/LICENSE.md %{buildroot}/usr/share/package-licenses/glmark2/ca3dfedb2b153392effc9ea7a45624d688901f90
cp %{_builddir}/glmark2-24a1139dcbfd86bd02065316eaa90559e39374e1/src/libmatrix/COPYING %{buildroot}/usr/share/package-licenses/glmark2/1e5d2af0ceaa596ea5d5f57ad2fe1dd75c7f2f7d
cp %{_builddir}/glmark2-24a1139dcbfd86bd02065316eaa90559e39374e1/src/libpng/LICENSE %{buildroot}/usr/share/package-licenses/glmark2/43172ff978bd688cd15143f7d2af6ccc63724a0b
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/glmark2
/usr/bin/glmark2-drm
/usr/bin/glmark2-es2
/usr/bin/glmark2-es2-drm
/usr/bin/glmark2-es2-wayland
/usr/bin/glmark2-wayland

%files data
%defattr(-,root,root,-)
/usr/share/glmark2/models/asteroid-high.3ds
/usr/share/glmark2/models/asteroid-low.3ds
/usr/share/glmark2/models/bunny.obj
/usr/share/glmark2/models/cat.3ds
/usr/share/glmark2/models/cube.3ds
/usr/share/glmark2/models/horse.3ds
/usr/share/glmark2/models/jellyfish.jobj
/usr/share/glmark2/shaders/README.shaders
/usr/share/glmark2/shaders/buffer-wireframe.frag
/usr/share/glmark2/shaders/buffer-wireframe.vert
/usr/share/glmark2/shaders/bump-height.frag
/usr/share/glmark2/shaders/bump-height.vert
/usr/share/glmark2/shaders/bump-normals-tangent.frag
/usr/share/glmark2/shaders/bump-normals-tangent.vert
/usr/share/glmark2/shaders/bump-normals.frag
/usr/share/glmark2/shaders/bump-normals.vert
/usr/share/glmark2/shaders/bump-poly.frag
/usr/share/glmark2/shaders/bump-poly.vert
/usr/share/glmark2/shaders/conditionals-step-conditional.all
/usr/share/glmark2/shaders/conditionals-step-simple.all
/usr/share/glmark2/shaders/conditionals.frag
/usr/share/glmark2/shaders/conditionals.vert
/usr/share/glmark2/shaders/depth.frag
/usr/share/glmark2/shaders/depth.vert
/usr/share/glmark2/shaders/desktop-blur.frag
/usr/share/glmark2/shaders/desktop.frag
/usr/share/glmark2/shaders/desktop.vert
/usr/share/glmark2/shaders/effect-2d-convolution.frag
/usr/share/glmark2/shaders/effect-2d.vert
/usr/share/glmark2/shaders/function-call.all
/usr/share/glmark2/shaders/function-step-low.all
/usr/share/glmark2/shaders/function-step-medium.all
/usr/share/glmark2/shaders/function.frag
/usr/share/glmark2/shaders/function.vert
/usr/share/glmark2/shaders/gradient.frag
/usr/share/glmark2/shaders/gradient.vert
/usr/share/glmark2/shaders/ideas-lamp-lit.frag
/usr/share/glmark2/shaders/ideas-lamp-lit.vert
/usr/share/glmark2/shaders/ideas-lamp-unlit.frag
/usr/share/glmark2/shaders/ideas-lamp-unlit.vert
/usr/share/glmark2/shaders/ideas-logo-flat.frag
/usr/share/glmark2/shaders/ideas-logo-flat.vert
/usr/share/glmark2/shaders/ideas-logo-shadow.frag
/usr/share/glmark2/shaders/ideas-logo-shadow.vert
/usr/share/glmark2/shaders/ideas-logo.frag
/usr/share/glmark2/shaders/ideas-logo.vert
/usr/share/glmark2/shaders/ideas-paper.frag
/usr/share/glmark2/shaders/ideas-paper.vert
/usr/share/glmark2/shaders/ideas-table.frag
/usr/share/glmark2/shaders/ideas-table.vert
/usr/share/glmark2/shaders/ideas-text.frag
/usr/share/glmark2/shaders/ideas-text.vert
/usr/share/glmark2/shaders/ideas-under-table.frag
/usr/share/glmark2/shaders/ideas-under-table.vert
/usr/share/glmark2/shaders/jellyfish.frag
/usr/share/glmark2/shaders/jellyfish.vert
/usr/share/glmark2/shaders/light-advanced.frag
/usr/share/glmark2/shaders/light-advanced.vert
/usr/share/glmark2/shaders/light-basic-tex-bilinear.frag
/usr/share/glmark2/shaders/light-basic-tex.frag
/usr/share/glmark2/shaders/light-basic-texgen.vert
/usr/share/glmark2/shaders/light-basic.frag
/usr/share/glmark2/shaders/light-basic.vert
/usr/share/glmark2/shaders/light-cel.frag
/usr/share/glmark2/shaders/light-phong.frag
/usr/share/glmark2/shaders/light-phong.vert
/usr/share/glmark2/shaders/light-refract.frag
/usr/share/glmark2/shaders/light-refract.vert
/usr/share/glmark2/shaders/loop-step-loop.all
/usr/share/glmark2/shaders/loop-step-simple.all
/usr/share/glmark2/shaders/loop.frag
/usr/share/glmark2/shaders/loop.vert
/usr/share/glmark2/shaders/pulsar-light.vert
/usr/share/glmark2/shaders/pulsar.vert
/usr/share/glmark2/shaders/shadow.frag
/usr/share/glmark2/shaders/shadow.vert
/usr/share/glmark2/shaders/terrain-blur.frag
/usr/share/glmark2/shaders/terrain-luminance.frag
/usr/share/glmark2/shaders/terrain-noise.frag
/usr/share/glmark2/shaders/terrain-normalmap.frag
/usr/share/glmark2/shaders/terrain-overlay.frag
/usr/share/glmark2/shaders/terrain-texture.vert
/usr/share/glmark2/shaders/terrain.frag
/usr/share/glmark2/shaders/terrain.vert
/usr/share/glmark2/shaders/text-renderer.frag
/usr/share/glmark2/shaders/text-renderer.vert
/usr/share/glmark2/textures/asteroid-height-map.png
/usr/share/glmark2/textures/asteroid-normal-map-tangent.png
/usr/share/glmark2/textures/asteroid-normal-map.png
/usr/share/glmark2/textures/crate-base.png
/usr/share/glmark2/textures/desktop-shadow-corner.png
/usr/share/glmark2/textures/desktop-shadow.png
/usr/share/glmark2/textures/desktop-window.png
/usr/share/glmark2/textures/effect-2d.png
/usr/share/glmark2/textures/glyph-atlas.png
/usr/share/glmark2/textures/jellyfish-caustics-01.png
/usr/share/glmark2/textures/jellyfish-caustics-02.png
/usr/share/glmark2/textures/jellyfish-caustics-03.png
/usr/share/glmark2/textures/jellyfish-caustics-04.png
/usr/share/glmark2/textures/jellyfish-caustics-05.png
/usr/share/glmark2/textures/jellyfish-caustics-06.png
/usr/share/glmark2/textures/jellyfish-caustics-07.png
/usr/share/glmark2/textures/jellyfish-caustics-08.png
/usr/share/glmark2/textures/jellyfish-caustics-09.png
/usr/share/glmark2/textures/jellyfish-caustics-10.png
/usr/share/glmark2/textures/jellyfish-caustics-11.png
/usr/share/glmark2/textures/jellyfish-caustics-12.png
/usr/share/glmark2/textures/jellyfish-caustics-13.png
/usr/share/glmark2/textures/jellyfish-caustics-14.png
/usr/share/glmark2/textures/jellyfish-caustics-15.png
/usr/share/glmark2/textures/jellyfish-caustics-16.png
/usr/share/glmark2/textures/jellyfish-caustics-17.png
/usr/share/glmark2/textures/jellyfish-caustics-18.png
/usr/share/glmark2/textures/jellyfish-caustics-19.png
/usr/share/glmark2/textures/jellyfish-caustics-20.png
/usr/share/glmark2/textures/jellyfish-caustics-21.png
/usr/share/glmark2/textures/jellyfish-caustics-22.png
/usr/share/glmark2/textures/jellyfish-caustics-23.png
/usr/share/glmark2/textures/jellyfish-caustics-24.png
/usr/share/glmark2/textures/jellyfish-caustics-25.png
/usr/share/glmark2/textures/jellyfish-caustics-26.png
/usr/share/glmark2/textures/jellyfish-caustics-27.png
/usr/share/glmark2/textures/jellyfish-caustics-28.png
/usr/share/glmark2/textures/jellyfish-caustics-29.png
/usr/share/glmark2/textures/jellyfish-caustics-30.png
/usr/share/glmark2/textures/jellyfish-caustics-31.png
/usr/share/glmark2/textures/jellyfish-caustics-32.png
/usr/share/glmark2/textures/jellyfish256.png
/usr/share/glmark2/textures/nasa1.png
/usr/share/glmark2/textures/nasa2.png
/usr/share/glmark2/textures/nasa3.png
/usr/share/glmark2/textures/terrain-backgrounddetailed6.jpg
/usr/share/glmark2/textures/terrain-grasslight-512-nm.jpg
/usr/share/glmark2/textures/terrain-grasslight-512.jpg

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/glmark2/1e5d2af0ceaa596ea5d5f57ad2fe1dd75c7f2f7d
/usr/share/package-licenses/glmark2/43172ff978bd688cd15143f7d2af6ccc63724a0b
/usr/share/package-licenses/glmark2/8624bcdae55baeef00cd11d5dfcfa60f68710a02
/usr/share/package-licenses/glmark2/ca3dfedb2b153392effc9ea7a45624d688901f90
/usr/share/package-licenses/glmark2/f044eb2afb2cff19b88e39a1d96d78c9d8bd2bfa

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/glmark2-drm.1
/usr/share/man/man1/glmark2-es2-drm.1
/usr/share/man/man1/glmark2-es2-wayland.1
/usr/share/man/man1/glmark2-es2.1
/usr/share/man/man1/glmark2-wayland.1
/usr/share/man/man1/glmark2.1
